name: Speed

on:
  workflow_dispatch:

  push:
    paths:
      - "./EternityBase"
      - "./sub/sub_merge_base64.txt"
      - "./sub/sub_merge_yaml.yml"

  schedule:
    # https://crontab.guru/
    - cron: "0 0,12 * * *"

jobs:
  main:
    name: SpeedTest
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
    
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: "latest"
          
      - uses: bahmutov/npm-install@v1.8.36
        with:
          working-directory: ./utils/localserver
          
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.11"
      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Tehran'
      - name: Install Requirements
        run: |
          pip install -r ./utils/requirements.txt
      - name: Run Lite Speedtest
        run: |
          sleep 5
          sudo sh ./utils/speedtest/speedtest2_yaml.sh
          python ./utils/speedtest/output.py
          
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin master
          git add EternityBase
          git add Eternity
          git add Eternity.txt
          git add ./sub/sub_merge.txt
          git add ./sub/sub_merge_base64.txt
          git add LogInfo.txt
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Tested"
          git push --force

      - name: Run Convertor & Formatter
        run: |
          sleep 5
          wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz
          tar -zxvf subconverter.tar.gz -C ./
          chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
          python ./utils/eternity_convert.py
          
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin master
          git add Eternity.yml
          git add Eternity
          git add README.md
          git add ./update/*
          git add LogInfo.txt
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Filtered"
          git push --force
     
      
